### PR TITLE
JEP-200 custom whitelist for JRubyXStream

### PR DESCRIPTION
**Pull request by jglick**
Cf. https://github.com/jenkinsci/jenkins/pull/3120.

@reviewbybees

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
🐝 whatever works

**Comment by jglick** [comment]
Actually consider this on hold since I thought of a cleaner approach to this—amending core so that the `BlacklistedTypesConverter` is given a lower priority than typical custom converters such as those installed by `JRubyXStream`. Needs some analysis and testing.

**Comment by jglick** [comment]
FTR with

```diff
diff --git a/src/test/java/jenkins/ruby/RubyViewTest.java b/src/test/java/jenkins/ruby/RubyViewTest.java
index e8c5101..92a45a0 100644
--- a/src/test/java/jenkins/ruby/RubyViewTest.java
+++ b/src/test/java/jenkins/ruby/RubyViewTest.java
@@ -1,6 +1,10 @@
 package jenkins.ruby;
 
 import com.gargoylesoftware.htmlunit.html.HtmlPage;
+import com.thoughtworks.xstream.converters.ConverterLookup;
+import hudson.model.Run;
+import java.lang.reflect.Field;
+import java.util.Set;
 import org.jvnet.hudson.test.HudsonTestCase;
 
 /**
@@ -17,4 +21,27 @@ public class RubyViewTest extends HudsonTestCase {
         assertTrue(text.contains("1+1=2"));
         assertTrue(text.contains("Hello from ERB [Jenkins]"));
     }
+
+    public void testConverters() throws Exception {
+        ConverterLookup cl = Run.XSTREAM.getConverterLookup();
+        Object dcl = ref(cl, "val$defaultConverterLookup");
+        Object pl = ref(dcl, "converters");
+        Set<?> set = (Set) ref(pl, "set");
+        for (Object pi : set) {
+            Object value = ref(pi, "value");
+            Object priority = ref(pi, "priority");
+            System.err.println(priority + " " + value.getClass().getName());
+        }
+    }
+
+    private static Object ref(Object o, String field) {
+        try {
+            Field f = o.getClass().getDeclaredField(field);
+            f.setAccessible(true);
+            return f.get(o);
+        } catch (Exception x) {
+            throw new RuntimeException(x);
+        }
+    }
+
 }
```

I see

```
10000 hudson.util.XStream2$2
10000 com.thoughtworks.xstream.converters.basic.NullConverter
10 hudson.model.Label$ConverterImpl
10 hudson.util.DescribableList$ConverterImpl
10 hudson.util.CopyOnWriteMap$Tree$ConverterImpl
10 hudson.util.xstream.ImmutableListConverter
10 hudson.util.xstream.ImmutableSetConverter
10 hudson.util.xstream.ImmutableSortedSetConverter
10 hudson.util.xstream.ImmutableMapConverter
10 hudson.util.RobustMapConverter
10 hudson.util.RobustCollectionConverter
0 org.jenkinsci.jruby.JavaProxyConverter
0 org.jenkinsci.jruby.RubyClassConverter
0 org.jenkinsci.jruby.RubyHashConverter
0 org.jenkinsci.jruby.RubyArrayConverter
0 org.jenkinsci.jruby.RubySymbolConverter
0 org.jenkinsci.jruby.RubyBooleanConverter
0 org.jenkinsci.jruby.RubyIntegerConverter
0 org.jenkinsci.jruby.RubyFixnumConverter
0 org.jenkinsci.jruby.RubyStringConverter
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.core.util.SelfStreamingInstanceChecker
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.enums.EnumMapConverter
0 com.thoughtworks.xstream.converters.enums.EnumSetConverter
0 com.thoughtworks.xstream.converters.enums.EnumConverter
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.extended.RegexPatternConverter
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.extended.ThrowableConverter
0 com.thoughtworks.xstream.converters.extended.SubjectConverter
0 com.thoughtworks.xstream.converters.extended.GregorianCalendarConverter
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.extended.LookAndFeelConverter
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.extended.ColorConverter
0 com.thoughtworks.xstream.converters.extended.FontConverter
0 com.thoughtworks.xstream.converters.extended.JavaFieldConverter
0 com.thoughtworks.xstream.converters.extended.JavaMethodConverter
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.extended.DynamicProxyConverter
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.extended.EncodedByteArrayConverter
0 com.thoughtworks.xstream.converters.collections.PropertiesConverter
0 com.thoughtworks.xstream.converters.collections.SingletonMapConverter
0 com.thoughtworks.xstream.converters.collections.SingletonCollectionConverter
0 com.thoughtworks.xstream.converters.collections.TreeSetConverter
0 com.thoughtworks.xstream.converters.collections.TreeMapConverter
0 com.thoughtworks.xstream.converters.collections.MapConverter
0 com.thoughtworks.xstream.converters.collections.CollectionConverter
0 com.thoughtworks.xstream.converters.collections.CharArrayConverter
0 com.thoughtworks.xstream.converters.collections.ArrayConverter
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.collections.BitSetConverter
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.basic.CharConverter
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
0 com.thoughtworks.xstream.converters.SingleValueConverterWrapper
-10 org.jenkinsci.jruby.JRubyXStreamConverter
-10 hudson.util.XStream2$AssociatedConverterImpl
-10 com.thoughtworks.xstream.converters.reflection.ExternalizableConverter
-10 com.thoughtworks.xstream.converters.reflection.SerializableConverter
-20 hudson.util.RobustReflectionConverter
```

**Comment by jglick** [comment]
My idea was to move `BlacklistedTypesConverter` down to, say, -5 priority, so that it would not override custom converters like the ones added by this plugin. But that looks dangerous. For example, `JavaMethodConverter` would then be enabled, despite `Method` being in the blacklist!

We could perhaps patch `JRubyXStream` to register its converters currently done at `PRIORITY_NORMAL` (0) to, say, `PRIORITY_VERY_HIGH + 1`, which would bypass `BlacklistedTypesConverter`. But `JRubyXStreamConverter` is currently registered at `PRIORITY_LOW`, presumably for a reason, and `JRubyXStreamClassFilter` shows that passing `IRubyObject` is necessary. So I think that approach is not going to work and we just need to stick with what we have here.

**Comment by jglick** [comment]
@reviewbybees done, no idea who maintains this stuff…

**Comment by oleg-nenashev** [comment]
@suryagaddipati was the last person who was merging something.

**Pull request merged**
